"""Generates src/unicode.rs: the Unicode letter (L*) and number (N*)
general categories as sorted code point ranges, for the pre-tokenizer
patterns (\\p{L} and \\p{N})."""

import sys
import unicodedata


def ranges(pred):
    out, start = [], None
    for cp in range(0x110000):
        ok = pred(unicodedata.category(chr(cp)))
        if ok and start is None:
            start = cp
        if not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def table(name, rs):
    body = "\n".join(f"    (0x{a:X}, 0x{b:X})," for a, b in rs)
    return f"const {name}: &[(u32, u32)] = &[\n{body}\n];\n"


src = f"""//! Unicode general categories used by the pre-tokenizer patterns.
//! Generated by scripts/gen_unicode.py from Unicode {unicodedata.unidata_version}; do not edit.

fn contains(table: &[(u32, u32)], c: char) -> bool {{
    let c = c as u32;
    table
        .binary_search_by(|&(a, b)| {{
            if b < c {{
                std::cmp::Ordering::Less
            }} else if a > c {{
                std::cmp::Ordering::Greater
            }} else {{
                std::cmp::Ordering::Equal
            }}
        }})
        .is_ok()
}}

/// `\\p{{L}}`: letters.
pub fn is_letter(c: char) -> bool {{
    if c.is_ascii() {{
        return c.is_ascii_alphabetic();
    }}
    contains(LETTER, c)
}}

/// `\\p{{N}}`: numbers (Nd, Nl, No).
pub fn is_number(c: char) -> bool {{
    if c.is_ascii() {{
        return c.is_ascii_digit();
    }}
    contains(NUMBER, c)
}}

{table("LETTER", ranges(lambda c: c[0] == "L"))}
{table("NUMBER", ranges(lambda c: c[0] == "N"))}"""
open(sys.argv[1] if len(sys.argv) > 1 else "src/unicode.rs", "w").write(src)
