"""Generates src/unicode.rs: the Unicode letter (L*) and number (N*)
general categories as sorted code point ranges, for the pre-tokenizer
patterns (\\p{L} and \\p{N}), and the tables for NFC normalization:
canonical combining classes, canonical decompositions and primary
compositions."""

import sys
import unicodedata


def ranges(pred):
    out, start = [], None
    for cp in range(0x110000):
        ok = pred(unicodedata.category(chr(cp)))
        if ok and start is None:
            start = cp
        if not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def table(name, rs):
    body = "\n".join(f"    (0x{a:X}, 0x{b:X})," for a, b in rs)
    return f"const {name}: &[(u32, u32)] = &[\n{body}\n];\n"


def hf_differences():
    """Combining marks and decompositions that Hugging Face tokenizers'
    NFC (the unicode-normalization crate, with older Unicode data) does not
    know. ferrolm follows the tokenizer, since matching its token ids is
    the point."""
    try:
        from tokenizers import normalizers
    except ImportError:
        return set(), set()
    n = normalizers.NFC()
    marks, decomps = set(), set()
    for cp in range(0x300, 0x110000):
        ch = chr(cp)
        if unicodedata.combining(ch):
            s = "a\u0301" + ch + "\u0316"
            if n.normalize_str(s) != unicodedata.normalize("NFC", s):
                marks.add(cp)
        d = unicodedata.decomposition(ch)
        if d and not d.startswith("<") and n.normalize_str(ch) != unicodedata.normalize("NFC", ch):
            decomps.add(cp)
    return marks, decomps


HF_MARKS, HF_DECOMPS = hf_differences()


def nfc_tables():
    ccc, decomp, comp = [], [], []
    for cp in range(0x110000):
        ch = chr(cp)
        if 0xAC00 <= cp <= 0xD7A3:
            continue  # Hangul syllables are handled algorithmically.
        c = unicodedata.combining(ch)
        if c and cp not in HF_MARKS:
            ccc.append((cp, c))
        d = unicodedata.decomposition(ch)
        if d and not d.startswith("<") and cp not in HF_DECOMPS:
            parts = [int(x, 16) for x in d.split()]
            decomp.append((cp, parts))
            # A primary composite: its pair recomposes to it under NFC.
            if len(parts) == 2 and unicodedata.normalize("NFC", chr(parts[0]) + chr(parts[1])) == ch:
                comp.append((parts[0], parts[1], cp))
    comp.sort()
    out = ""
    if HF_MARKS or HF_DECOMPS:
        out += "// As in Hugging Face tokenizers, these newer marks have class 0: "
        out += " ".join(f"U+{c:04X}" for c in sorted(HF_MARKS)) + "\n"
        out += "// and these characters do not decompose: "
        out += " ".join(f"U+{c:04X}" for c in sorted(HF_DECOMPS)) + "\n"
    out += "/// Canonical combining classes (non-zero only).\nconst CCC: &[(u32, u8)] = &[\n"
    out += "\n".join(f"    (0x{a:X}, {c})," for a, c in ccc) + "\n];\n\n"
    out += "/// Canonical decompositions, one level (apply recursively).\nconst DECOMP: &[(u32, u32, u32)] = &[\n"
    out += "\n".join(f"    (0x{a:X}, 0x{p[0]:X}, 0x{(p[1] if len(p) > 1 else 0):X})," for a, p in decomp) + "\n];\n\n"
    out += "/// Primary compositions: (first, second, composite), sorted.\nconst COMP: &[(u32, u32, u32)] = &[\n"
    out += "\n".join(f"    (0x{a:X}, 0x{b:X}, 0x{c:X})," for a, b, c in comp) + "\n];\n"
    return out


src = f"""//! Unicode general categories used by the pre-tokenizer patterns.
//! Generated by scripts/gen_unicode.py from Unicode {unicodedata.unidata_version}, with NFC data
//! aligned to Hugging Face tokenizers; do not edit.

fn contains(table: &[(u32, u32)], c: char) -> bool {{
    let c = c as u32;
    table
        .binary_search_by(|&(a, b)| {{
            if b < c {{
                std::cmp::Ordering::Less
            }} else if a > c {{
                std::cmp::Ordering::Greater
            }} else {{
                std::cmp::Ordering::Equal
            }}
        }})
        .is_ok()
}}

/// `\\p{{L}}`: letters.
pub fn is_letter(c: char) -> bool {{
    if c.is_ascii() {{
        return c.is_ascii_alphabetic();
    }}
    contains(LETTER, c)
}}

/// Unicode normalization form C.
pub fn nfc(s: &str) -> std::borrow::Cow<'_, str> {{
    // Below U+0300 nothing decomposes or composes.
    if s.chars().all(|c| (c as u32) < 0x300) {{
        return std::borrow::Cow::Borrowed(s);
    }}
    let mut d = Vec::with_capacity(s.len());
    for c in s.chars() {{
        decompose(c as u32, &mut d);
    }}
    // Canonical ordering: sort each run of non-starters by class, stably.
    let mut i = 0;
    while i < d.len() {{
        if ccc(d[i]) == 0 {{
            i += 1;
            continue;
        }}
        let start = i;
        while i < d.len() && ccc(d[i]) != 0 {{
            i += 1;
        }}
        d[start..i].sort_by_key(|&c| ccc(c));
    }}
    let mut out: Vec<u32> = Vec::with_capacity(d.len());
    let mut starter: Option<usize> = None;
    let mut last = 0u8;
    for c in d {{
        let cc = ccc(c);
        if let Some(st) = starter {{
            let adjacent = out.len() - 1 == st;
            if (adjacent || (last != 0 && last < cc)) && let Some(x) = compose(out[st], c) {{
                out[st] = x;
                continue;
            }}
        }}
        if cc == 0 {{
            starter = Some(out.len());
        }}
        last = cc;
        out.push(c);
    }}
    std::borrow::Cow::Owned(out.into_iter().filter_map(char::from_u32).collect())
}}

const S_BASE: u32 = 0xAC00;
const L_BASE: u32 = 0x1100;
const V_BASE: u32 = 0x1161;
const T_BASE: u32 = 0x11A7;
const T_COUNT: u32 = 28;
const N_COUNT: u32 = 21 * T_COUNT;
const S_COUNT: u32 = 19 * N_COUNT;

fn ccc(c: u32) -> u8 {{
    CCC.binary_search_by_key(&c, |e| e.0).map_or(0, |i| CCC[i].1)
}}

fn decompose(c: u32, out: &mut Vec<u32>) {{
    if (S_BASE..S_BASE + S_COUNT).contains(&c) {{
        let s = c - S_BASE;
        out.push(L_BASE + s / N_COUNT);
        out.push(V_BASE + (s % N_COUNT) / T_COUNT);
        if s % T_COUNT != 0 {{
            out.push(T_BASE + s % T_COUNT);
        }}
        return;
    }}
    match DECOMP.binary_search_by_key(&c, |e| e.0) {{
        Ok(i) => {{
            let (_, a, b) = DECOMP[i];
            decompose(a, out);
            if b != 0 {{
                decompose(b, out);
            }}
        }}
        Err(_) => out.push(c),
    }}
}}

fn compose(a: u32, b: u32) -> Option<u32> {{
    if (L_BASE..L_BASE + 19).contains(&a) && (V_BASE..V_BASE + 21).contains(&b) {{
        return Some(S_BASE + ((a - L_BASE) * 21 + (b - V_BASE)) * T_COUNT);
    }}
    if (S_BASE..S_BASE + S_COUNT).contains(&a) && (a - S_BASE) % T_COUNT == 0 && (T_BASE + 1..T_BASE + T_COUNT).contains(&b) {{
        return Some(a + (b - T_BASE));
    }}
    COMP.binary_search_by(|e| (e.0, e.1).cmp(&(a, b))).ok().map(|i| COMP[i].2)
}}

/// `\\p{{N}}`: numbers (Nd, Nl, No).
pub fn is_number(c: char) -> bool {{
    if c.is_ascii() {{
        return c.is_ascii_digit();
    }}
    contains(NUMBER, c)
}}

{table("LETTER", ranges(lambda c: c[0] == "L"))}
{table("NUMBER", ranges(lambda c: c[0] == "N"))}
{nfc_tables()}"""
open(sys.argv[1] if len(sys.argv) > 1 else "src/unicode.rs", "w").write(src)
